# Generated by Django 3.2.6 on 2021-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_myinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to='about_image/'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='mobile_no',
            field=models.IntegerField(max_length=250),
        ),
    ]
