# Generated by Django 3.2.6 on 2021-08-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20210822_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='mobile_no',
            field=models.CharField(max_length=250),
        ),
    ]
